# Generated by Django 6.0.6 on 2026-06-04 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('moderador', 'Moderador'), ('usuario', 'Usuario')], default='usuario', max_length=20)),
                ('objetivo', models.CharField(blank=True, choices=[('estetico', 'Estético'), ('hipertrofia', 'Hipertrofia'), ('salud', 'Salud'), ('nutricion', 'Nutrición'), ('recuperar', 'Recuperación')], max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Usuario',
                'verbose_name_plural': 'Perfiles Usuarios',
            },
        ),
    ]
