# Generated by Django 4.2.11 on 2026-06-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_personalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='peso_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('estetico', 'Estético'), ('hipertrofia', 'Hipertrofia'), ('salud', 'Salud'), ('nutricion', 'Nutrición'), ('recuperar', 'Recuperación')], max_length=50, null=True),
        ),
    ]
