# Generated by Django 4.2.11 on 2026-08-13 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_perfilusuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=140, unique=True)),
                ('descripcion', models.TextField()),
                ('instrucciones', models.TextField(help_text='Escribe un paso de ejecución por cada línea.')),
                ('errores_comunes', models.TextField(blank=True)),
                ('precauciones', models.TextField(blank=True)),
                ('grupo_muscular', models.CharField(choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('hombros', 'Hombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('cuadriceps', 'Cuádriceps'), ('femorales', 'Femorales'), ('gluteos', 'Glúteos'), ('pantorrillas', 'Pantorrillas'), ('abdomen', 'Abdomen'), ('cuerpo_completo', 'Cuerpo completo'), ('cardio', 'Cardio')], max_length=30)),
                ('musculos_secundarios', models.CharField(blank=True, max_length=180)),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=20)),
                ('tipo_equipo', models.CharField(choices=[('barra', 'Barra'), ('mancuernas', 'Mancuernas'), ('maquina', 'Máquina'), ('polea', 'Polea'), ('peso_corporal', 'Peso corporal'), ('banda_elastica', 'Banda elástica'), ('kettlebell', 'Kettlebell'), ('cardio', 'Máquina de cardio'), ('otro', 'Otro')], max_length=30)),
                ('equipo_necesario', models.CharField(blank=True, max_length=180)),
                ('tipo_medicion', models.CharField(choices=[('repeticiones', 'Repeticiones'), ('tiempo', 'Tiempo'), ('distancia', 'Distancia')], default='repeticiones', max_length=20)),
                ('puntos_base', models.PositiveSmallIntegerField(default=10)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='ejercicios/portadas/')),
                ('modelo_3d', models.FileField(blank=True, null=True, upload_to='ejercicios/modelos_3d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf'])])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['grupo_muscular', 'nombre'],
            },
        ),
    ]
