# Generated by Django 4.2.11 on 2026-08-14 01:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0005_ejercicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('nombre', models.CharField(max_length=120)),
                ('enfoque', models.CharField(blank=True, max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Día del plan',
                'verbose_name_plural': 'Días del plan',
                'ordering': ['fase', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PlanEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=160, unique=True)),
                ('objetivo', models.CharField(choices=[('estetico', 'Estético'), ('hipertrofia', 'Hipertrofia'), ('salud', 'Salud'), ('nutricion', 'Nutrición'), ('recuperar', 'Recuperación')], max_length=20)),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=20)),
                ('descripcion', models.TextField()),
                ('duracion_semanas', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('dias_por_semana', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de entrenamiento',
                'verbose_name_plural': 'Planes de entrenamiento',
                'ordering': ['objetivo', 'nivel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='FasePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('semana_inicio', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('semana_fin', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='gym_app.planentrenamiento')),
            ],
            options={
                'verbose_name': 'Fase del plan',
                'verbose_name_plural': 'Fases del plan',
                'ordering': ['plan', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='EjercicioProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('series', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('repeticiones_min', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('repeticiones_max', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7200)])),
                ('distancia_metros', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('descanso_segundos', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1800)])),
                ('esfuerzo_objetivo', models.PositiveSmallIntegerField(default=7, help_text='Esfuerzo percibido del 1 al 10. Un valor de 7 significa esfuerzo moderado-alto.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('obligatorio', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_programados', to='gym_app.diaplan')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='gym_app.ejercicio')),
            ],
            options={
                'verbose_name': 'Ejercicio programado',
                'verbose_name_plural': 'Ejercicios programados',
                'ordering': ['dia', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='diaplan',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='gym_app.faseplan'),
        ),
        migrations.AddConstraint(
            model_name='faseplan',
            constraint=models.UniqueConstraint(fields=('plan', 'orden'), name='fase_orden_unico_por_plan'),
        ),
        migrations.AddConstraint(
            model_name='ejercicioprogramado',
            constraint=models.UniqueConstraint(fields=('dia', 'orden'), name='ejercicio_orden_unico_por_dia'),
        ),
        migrations.AddConstraint(
            model_name='ejercicioprogramado',
            constraint=models.UniqueConstraint(fields=('dia', 'ejercicio'), name='ejercicio_unico_por_dia'),
        ),
        migrations.AddConstraint(
            model_name='diaplan',
            constraint=models.UniqueConstraint(fields=('fase', 'numero'), name='dia_numero_unico_por_fase'),
        ),
    ]
