# Generated by Django 4.2.11 on 2026-08-14 02:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym_app', '0006_diaplan_planentrenamiento_faseplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionPlanUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('abandonado', 'Abandonado')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='gym_app.planentrenamiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan asignado a usuario',
                'verbose_name_plural': 'Planes asignados a usuarios',
                'ordering': ['-fecha_inicio', 'usuario'],
            },
        ),
        migrations.CreateModel(
            name='HorarioPlanUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dia_plan', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_preferida', models.TimeField(blank=True, null=True)),
                ('recordatorio_activo', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='gym_app.asignacionplanusuario')),
            ],
            options={
                'verbose_name': 'Horario del plan',
                'verbose_name_plural': 'Horarios del plan',
                'ordering': ['asignacion', 'dia_semana'],
            },
        ),
        migrations.AddConstraint(
            model_name='horarioplanusuario',
            constraint=models.UniqueConstraint(fields=('asignacion', 'numero_dia_plan'), name='numero_dia_unico_por_asignacion'),
        ),
        migrations.AddConstraint(
            model_name='horarioplanusuario',
            constraint=models.UniqueConstraint(fields=('asignacion', 'dia_semana'), name='dia_semana_unico_por_asignacion'),
        ),
    ]
