# Generated by Django 4.2.11 on 2026-08-14 03:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0007_asignacionplanusuario_horarioplanusuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('semana_plan', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('puntos_obtenidos', models.PositiveIntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='gym_app.asignacionplanusuario')),
                ('dia_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_realizadas', to='gym_app.diaplan')),
            ],
            options={
                'verbose_name': 'Sesión de entrenamiento',
                'verbose_name_plural': 'Sesiones de entrenamiento',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EjercicioSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('series_completadas', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)])),
                ('repeticiones_realizadas', models.PositiveIntegerField(blank=True, null=True)),
                ('duracion_realizada_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('distancia_realizada_metros', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_utilizado_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('puntos_obtenidos', models.PositiveSmallIntegerField(default=0)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=250)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ejercicio_programado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_realizados', to='gym_app.ejercicioprogramado')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='gym_app.sesionentrenamiento')),
            ],
            options={
                'verbose_name': 'Ejercicio de una sesión',
                'verbose_name_plural': 'Ejercicios de las sesiones',
                'ordering': ['sesion', 'ejercicio_programado__orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='sesionentrenamiento',
            constraint=models.UniqueConstraint(fields=('asignacion', 'fecha'), name='sesion_unica_por_asignacion_y_fecha'),
        ),
        migrations.AddConstraint(
            model_name='sesionentrenamiento',
            constraint=models.UniqueConstraint(fields=('asignacion', 'semana_plan', 'dia_plan'), name='dia_plan_unico_por_semana_asignada'),
        ),
        migrations.AddConstraint(
            model_name='ejerciciosesion',
            constraint=models.UniqueConstraint(fields=('sesion', 'ejercicio_programado'), name='ejercicio_unico_por_sesion'),
        ),
    ]
