# Generated by Django 4.2.11 on 2026-08-14 19:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0008_sesionentrenamiento_ejerciciosesion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieEjercicioSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('repeticiones_realizadas', models.PositiveIntegerField(blank=True, null=True)),
                ('duracion_realizada_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('distancia_realizada_metros', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_utilizado_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('descanso_hasta', models.DateTimeField(blank=True, null=True)),
                ('descanso_omitido', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ejercicio_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='gym_app.ejerciciosesion')),
            ],
            options={
                'verbose_name': 'Serie realizada',
                'verbose_name_plural': 'Series realizadas',
                'ordering': ['ejercicio_sesion', 'numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='serieejerciciosesion',
            constraint=models.UniqueConstraint(fields=('ejercicio_sesion', 'numero'), name='numero_serie_unico_por_ejercicio'),
        ),
    ]
