# Generated by Django 4.2.11 on 2026-09-07 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0011_personalizacion_rutina_y_nutricion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='altura_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='mensajes_entregados',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
