# Generated by Django 4.2.11 on 2026-09-07 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym_app', '0012_perfilusuario_altura_cm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoAmigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('imagen', models.ImageField(blank=True, upload_to='grupos/')),
                ('invitacion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='priorizar_tren_inferior',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RutinaGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('ejercicios', models.ManyToManyField(to='gym_app.ejercicio')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='gym_app.grupoamigos')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.DateField()),
                ('clasificacion', models.JSONField(default=list)),
                ('insignia', models.BooleanField(default=False)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.grupoamigos')),
            ],
        ),
        migrations.CreateModel(
            name='RecompensaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('puntos', models.PositiveIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym_app.ejercicio')),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gym_app.ejerciciosesion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='gym_app.rutinagrupal')),
                ('sesion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gym_app.sesionentrenamiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntegranteGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='gym_app.grupoamigos')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaComprometido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cancelado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvisoSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='resultadogrupo',
            constraint=models.UniqueConstraint(fields=('grupo', 'semana'), name='resultado_grupo_semana'),
        ),
        migrations.AddConstraint(
            model_name='recompensaejercicio',
            constraint=models.UniqueConstraint(fields=('usuario', 'ejercicio', 'fecha'), name='recompensa_ejercicio_usuario_dia'),
        ),
        migrations.AddConstraint(
            model_name='participaciongrupal',
            constraint=models.UniqueConstraint(fields=('rutina', 'usuario'), name='participacion_unica'),
        ),
        migrations.AddConstraint(
            model_name='diacomprometido',
            constraint=models.UniqueConstraint(fields=('usuario', 'fecha'), name='compromiso_usuario_fecha'),
        ),
    ]
