# Generated by Django 4.2.11 on 2026-09-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0014_conservar_puntos_y_calendarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=64, unique=True)),
                ('ventana', models.BigIntegerField(db_index=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
